config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  get 'compare/view'
  get 'compare/comparison'
  get 'history/view'

  resources :charities
  resources :donations
  root 'charities#index'
  mount Rapidfire::Engine => "/rapidfire"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/charity.rb
class Charity < ActiveRecord::Base
end

app/models/donation.rb
class Donation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

   def can_administer?
      current_user.try(:admin?)
    end
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  before_action :set_charity, only: [:show, :edit, :update, :destroy]

  # GET /charities
  # GET /charities.json
  def index
    @charities = Charity.all
  end

  # GET /charities/1
  # GET /charities/1.json
  def show
  end

  # GET /charities/new
  def new
    @charity = Charity.new
  end

  # GET /charities/1/edit
  def edit
  end

  # POST /charities
  # POST /charities.json
  def create
    @charity = Charity.new(charity_params)
    @charity.total = 0;
    respond_to do |format|
      if @charity.save
        format.html { redirect_to @charity, notice: 'Charity was successfully created.' }
        format.json { render :show, status: :created, location: @charity }
      else
        format.html { render :new }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charities/1
  # PATCH/PUT /charities/1.json
  def update
    respond_to do |format|
      if @charity.update(charity_params)
        format.html { redirect_to @charity, notice: 'Charity was successfully updated.' }
        format.json { render :show, status: :ok, location: @charity }
      else
        format.html { render :edit }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charities/1
  # DELETE /charities/1.json
  def destroy
    @charity.destroy
    respond_to do |format|
      format.html { redirect_to charities_url, notice: 'Charity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charity
      @charity = Charity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charity_params
      params.require(:charity).permit(:name, :description, :address, :website, :email, :POC, :phone, :tax_code, :total)
    end
end

app/controllers/compare_controller.rb
class CompareController < ApplicationController
  	def view
  		@charities = Charity.all	
	end

	#POST
	def comparison
		
	end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)
    @charity = Charity.find_by(name:@donation.charity)
    @charity.total += @donation.amount
    @charity.save

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
  	@charity = Charity.find_by(name:@donation.charity)
  	@charity.total -= @donation.amount
    respond_to do |format|
      if @donation.update(donation_params)
	    @charity.total += @donation.amount
	    @charity.save
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
      	@charity.total += @donation.amount
	    @charity.save
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
  	@charity = Charity.find_by(name:@donation.charity)
	@charity.total -= @donation.amount
	@charity.save
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:amount, :charity, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/helpers/compare_helper.rb
module CompareHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/charities/_form.html.erb
<%= form_for(@charity) do |f| %>
  <% if @charity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charity.errors.count, "error") %> prohibited this charity from being saved:</h2>

      <ul>
      <% @charity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => true, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :required => true, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :POC %><br>
    <%= f.text_field :POC, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tax_code %><br>
    <%= f.text_field :tax_code, :class => "form-control" %>
  </div>
  <!--<div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div> -->
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-default btn-sm"%>
  </div>
<% end %>

app/views/charities/edit.html.erb
<% if current_user.try(:admin?) %>
<h1>Editing Charity</h1>

<%= render 'form' %>

<%= link_to 'View Charity Details', @charity, :class => "btn btn-default btn-sm" %> |
<%= link_to 'Back', charities_path, :class => "btn btn-default btn-sm" %>
<% end %>

app/views/charities/index.html.erb
<body>

  <p id="notice"><%= notice %></p>
  <% if current_user.try(:admin?) %>
  <h1>All Charities</h1>

  <table class = "table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Total</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @charities.each do |charity| %>
        <tr>
          <td><%= charity.name %></td>
          <td><%= charity.description %></td>
          <td><%= charity.total %></td>
          <td><%= link_to 'View Details', charity, :class => "btn btn-default btn-sm" %></td>
          <td><%= link_to 'Edit Details', edit_charity_path(charity), :class => "btn btn-default btn-sm" %></td>
          <td><%= link_to 'Delete', charity, :class => "btn btn-default btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Add New Charity', new_charity_path, :class => "btn btn-default btn-sm" %>
  <% end %>
</body>

app/views/charities/new.html.erb
<h1>New Charity</h1>

<%= render 'form' %>

<%= link_to 'Back', charities_path, :class => "btn btn-default btn-sm" %>

app/views/charities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @charity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @charity.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @charity.address %>
</p>

<p>
  <strong>Website:</strong>
  <%= @charity.website %>
</p>

<p>
  <strong>Email:</strong>
  <%= @charity.email %>
</p>

<p>
  <strong>Poc:</strong>
  <%= @charity.POC %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @charity.phone %>
</p>

<p>
  <strong>Tax code:</strong>
  <%= @charity.tax_code %>
</p>

<p>
  <strong>Total:</strong>
  <% total = 0 %>
  <% Donation.where(charity:@charity.name).find_each do |donation| %>
      <% total += donation.amount %>
  <% end %>
  <%= @charity.total = total %>
  <% @charity.save %>
</p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
 
    <% Donation.where(charity:@charity.name).find_each do |donation| %>
      <tr>
        <td><%= donation.amount %></td>
        <td><%= donation.date %></td>
        <td><%= link_to 'View Details', donation, :class => "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Edit Details', edit_donation_path(donation), :class => "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Delete', donation, :class => "btn btn-default btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit Charity Details', edit_charity_path(@charity), :class => "btn btn-default btn-sm" %> |
<%= link_to 'Back', charities_path, :class => "btn btn-default btn-sm" %>

app/views/compare/view.html.erb
<body>

  <p id="notice"><%= notice %></p>
  <% if current_user.try(:admin?) %>
  <h1>All Charities</h1>

  <%= form_for(@compare) do |f| %>
  <% if @compare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compare.errors.count, "error") %> prohibited this compare from being saved:</h2>

      <ul>
      <% @compare.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :charity %><br>
    <%= f.collection_select :charity, Charity.all, :name,:name, {prompt: "Select a charity"}, :required =>true, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :charity %><br>
    <%= f.collection_select :charity, Charity.all, :name,:name, {prompt: "Select a charity"}, :required =>true, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :charity %><br>
    <%= f.collection_select :charity, Charity.all, :name,:name, {prompt: "Select a charity"}, :required =>true, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-default btn-sm" %>
  </div>
<% end %>
</body>

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :amount %><br>
    <%= f.text_field :amount, :required => true, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :charity %><br>
    <%= f.collection_select :charity, Charity.all, :name,:name, {prompt: "Select a charity"}, :required =>true, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :date %><br>
    <%= f.datetime_select :date, :required => true %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-default btn-sm" %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing Donation</h1>

<%= render 'form' %>

<%= button_to 'View Details', @donation %> |
<%= button_to 'Back', donations_path %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_user.try(:admin?) %>
<div class="center-block">
<h1>All Donations</h1>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Charity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.amount %></td>
        <td><%= donation.charity %></td>
        <td><%= link_to 'View Details', donation, :class => "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Edit Details', edit_donation_path(donation), :class => "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Delete', donation, :class => "btn btn-default btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Donation', new_donation_path, :class => "btn btn-default btn-sm" %>
<% end %>

app/views/donations/new.html.erb
<h1>New Donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path, :class => "btn btn-default btn-sm" %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @donation.amount %>
</p>

<p>
  <strong>Charity:</strong>
  <%= @donation.charity %>
</p>

<p>
  <strong>Date:</strong>
  <%= @donation.date %>
</p>

<%= link_to 'Edit Donation Details', edit_donation_path(@donation), :class => "btn btn-default btn-sm" %> |
<%= link_to 'Back', donations_path, :class => "btn btn-default btn-sm" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <!--<img src="/assets/Logo.png" alt="logo feed" style="width:304px;height:128px"/>-->
   <%= image_tag "Logo.png", :alt => "Logo", :style => "width:304px;height:128px" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
	<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <Title>Black Rock</Title>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <% if current_user.try(:admin?) %>
                <li><a href="https://rocky-badlands-5623.herokuapp.com/charities"> Charities</a></li>
                <li><a href="https://rocky-badlands-5623.herokuapp.com/donations"> Donations</a></li>
              <% end %>
              <li><a href="https://rocky-badlands-5623.herokuapp.com/rapidfire"> Polls</a></li>
              
              
            </ul>
            <ul class="nav pull-right">
			  
			  <% if user_signed_in? %>
			    <li id="fat-menu" class="dropdown">
			      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
			        Account <b class="caret"></b>
			      </a>
			      <ul class="dropdown-menu">
              <li><%= link_to "Profile", "https://rocky-badlands-5623.herokuapp.com/users/edit" %></li>
              
              <li class="divider"></li>
              <li>
                <%= link_to "Logout", "https://rocky-badlands-5623.herokuapp.com/users/sign_out", :method => :delete %>
              </li>
            </ul>
			    </li>
			  <% else %>
			    <li><%= link_to "Sign in", new_user_session_path %></li>
			  <% end %>
			</ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

<div style="padding: 0% 10% 10% 10%">
  <body>

  <%= yield %>

  </body>
</div>
</html>

app/views/rapidfire/answer_groups/new.html.erb
<h2>Please answer these Questions</h2>
<hr/>

<%= form_for([@question_group, @answer_group_builder]) do |f| %>
  <%- @answer_group_builder.answers.each do |answer| %>
    <%= f.fields_for("#{answer.question.id}", answer) do |answer_form| %>
    	<div class="form-group">
      <%= render_answer_form_helper(answer, answer_form) %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
  <%= f.submit "Save", :class => "btn btn-default btn-sm" %>
  </div>
<% end %>

app/views/rapidfire/answers/_checkbox.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<%= f.label :answer_text, answer.question.question_text %>
<%= f.fields_for :answer_text do |af| %>
  <%- answer.question.options.each do |option| %>
    <%= af.label option do %>
      <%= af.check_box nil, { id: nil, checked: checkbox_checked?(answer, option) }, option %>
      <%= option %>
    <% end %>
  <% end %>
<% end %>

app/views/rapidfire/answers/_date.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<%= f.label :answer_text, answer.question.question_text %>
<%= f.text_field :answer_text %>

app/views/rapidfire/answers/_errors.html.erb
<%- if answer.errors.any? %>
  <ul>
    <%- answer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/rapidfire/answers/_long.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<%= f.label :answer_text, answer.question.question_text %>
<%= f.text_area :answer_text, :rows => 5 %>

app/views/rapidfire/answers/_numeric.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<%= f.label :answer_text, answer.question.question_text %>
<%= f.text_field :answer_text %>

app/views/rapidfire/answers/_radio.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<%= f.label :answer_text, answer.question.question_text %>
<%- answer.question.options.each do |option| %>
  <%= f.label "answer_text_#{option}", option do %>
    <%= f.radio_button :answer_text, option %>
    <%= option %>
  <% end %>
<% end %>

app/views/rapidfire/answers/_select.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<%= f.label :answer_text, answer.question.question_text %>
<%= f.select :answer_text, answer.question.options, include_blank: true %>

app/views/rapidfire/answers/_short.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<%= f.label :answer_text, answer.question.question_text %>
<%= f.text_field :answer_text %>

app/views/rapidfire/question_groups/_form.html.erb
<div style="padding: 0% 20% 0% 20%">
<h3><%= question_group.new_record? ? "New Group" : "Edit Group" %></h3>

<%= form_for question_group do |f| %>
  <%- if question_group.errors.any? %>
    <ul>
      <%- question_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control" %>
</div>
  <%= f.submit "Create Question Group", :class => "btn btn-default btn-sm"%>
<% end %>
</div>

app/views/rapidfire/question_groups/_question_group.html.erb
<tr id= "question_group_<%= question_group.id %>">
  <td>
    <% if can_administer? %>
      <%= link_to question_group.name, question_group_questions_path(question_group), :class => "btn btn-default btn-sm" %>
    <% else %>
      <%= question_group.name %>
    <% end %>
  </td>
  <td>
    <ul class="horizontal-list">
      <li><%= link_to "Answer Questions", new_question_group_answer_group_path(question_group) %></li>
      <% if can_administer? %>
        <li><%= link_to "Results", [:results, question_group] %></li>
        <li><%= link_to "Delete", [question_group], method: :delete %></li>
      <% end %>
    </ul>
  </td>
</tr>

app/views/rapidfire/question_groups/index.html.erb
<h2>
  Question Groups
  <% if can_administer? %>
    <%= link_to "New Group", new_question_group_path, :class => "btn btn-default btn-sm" %>
  <% end %>
</h2>
<hr/>

<table>
  <colgroup>
    <col>
    <col width="250">
  </colgroup>
  <thead>
    <tr>
      <th>Question Group</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "question_group", collection: @question_groups %>
  </tbody>
</table>

app/views/rapidfire/question_groups/new.html.erb
<%= render partial: 'form', locals: {question_group: @question_group} %>

app/views/rapidfire/question_groups/results.html.erb
<h1>Results</h1>

<%- @question_group_results.each do |result| %>
  <div>
    <h4><%= result.question.question_text %></h4>
    <p>
      <%- if result.results.is_a?(Array) %>
        <ol>
          <%- result.results.each do |answer| %>
            <li><%= answer %></li>
          <% end %>
        </ol>
      <% elsif result.results.is_a?(Hash) %>
        <table>
          <thead>
            <tr>
              <th>Option</th>
              <th>Count</th>
            </tr>
          </thead>
          <tbody>
            <%- result.results.each do |option, count| %>
              <tr>
                <td><%= option %></td>
                <td><%= count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
  </div>
<% end %>

app/views/rapidfire/questions/_form.html.erb
<div style="padding: 0% 10% 0% 10%">
<h3>Question</h3>

<%= form_for form, as: :question, url: url, method: method do |f| %>
  <%- unless form.errors.empty? %>
    <ul>
      <%- form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<div class="form-group">
  <%= f.label :type %>
  <%= f.select :type, ::Rapidfire::QuestionForm::QUESTION_TYPES, {}, id: "question_type", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :question_text %>
  <%= f.text_field :question_text, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :answer_options %>
  <%= f.text_area :answer_options, rows: 5, :class => "form-control" %>
</div>
  <h4>Other options</h4>
  <hr/>
<div class="form-group">
  <%= f.label :answer_presence %>
  <%= f.check_box :answer_presence %>
</div>
<div class="form-group">
  <%= f.label :answer_minimum_length %>
  <%= f.text_field :answer_minimum_length, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :answer_maximum_length %>
  <%= f.text_field :answer_maximum_length, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :answer_greater_than_or_equal_to %>
  <%= f.text_field :answer_greater_than_or_equal_to, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :answer_less_than_or_equal_to %>
  <%= f.text_field :answer_less_than_or_equal_to, :class => "form-control" %>
</div>

  <%= f.submit submit_text, :class => "btn btn-default btn-sm" %>
<% end %>
</div>

app/views/rapidfire/questions/_question.html.erb
<tr id="question_<%= question.id %>">
  <td><%= question.question_text %></td>
  <td>
    <ul class="horizontal-list">
      <li><%= link_to "Edit", [:edit, question.question_group, question] %></li>
      <li><%= link_to "Delete", [question.question_group, question], method: :delete %></li>
    </ul>
  </td>
</tr>

app/views/rapidfire/questions/edit.html.erb
<%= render partial: 'form', locals: { form: @question_form, url: question_group_question_path(@question_group, @question), method: :put, submit_text: 'Update Question' } %>

app/views/rapidfire/questions/index.html.erb
<h2>
  Questions
  <%= link_to "Add New Question", new_question_group_question_path(@question_group), :class => "btn btn-default btn-sm" %>
</h2>
<hr/>

<table>
  <colgroup>
    <col>
    <col width="250">
  </colgroup>
  <thead>
    <tr>
      <th>Question</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "question", collection: @questions %>
  </tbody>
</table>

app/views/rapidfire/questions/new.html.erb
<%= render partial: 'form', locals: { form: @question_form, url: question_group_questions_path(@question_group), method: :post, submit_text: 'Create Question' } %>